DROP TABLE HF_JOB CASCADE CONSTRAINTS PURGE;

DROP TABLE HF_COUNTER CASCADE CONSTRAINTS PURGE;

DROP TABLE HF_AGGREGATED_COUNTER CASCADE CONSTRAINTS PURGE;

DROP TABLE HF_DISTRIBUTED_LOCK CASCADE CONSTRAINTS PURGE;

DROP TABLE HF_HASH CASCADE CONSTRAINTS PURGE;

DROP TABLE HF_JOB_PARAMETER CASCADE CONSTRAINTS PURGE;

DROP TABLE HF_JOB_QUEUE CASCADE CONSTRAINTS PURGE;

DROP TABLE HF_JOB_STATE CASCADE CONSTRAINTS PURGE;

DROP TABLE HF_SERVER CASCADE CONSTRAINTS PURGE;

DROP TABLE HF_SET CASCADE CONSTRAINTS PURGE;

DROP TABLE HF_LIST CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE HF_SEQUENCE;

DROP SEQUENCE HF_JOB_ID_SEQ;