TRUNCATE TABLE HF_JOB DROP STORAGE;

TRUNCATE TABLE HF_COUNTER DROP STORAGE;

TRUNCATE TABLE HF_AGGREGATED_COUNTER DROP STORAGE;

TRUNCATE TABLE HF_DISTRIBUTED_LOCK DROP STORAGE;

TRUNCATE TABLE HF_HASH DROP STORAGE;

TRUNCATE TABLE HF_JOB_PARAMETER DROP STORAGE;

TRUNCATE TABLE HF_JOB_QUEUE DROP STORAGE;

TRUNCATE TABLE HF_JOB_STATE DROP STORAGE;

TRUNCATE TABLE HF_SERVER DROP STORAGE;

TRUNCATE TABLE HF_SET DROP STORAGE;

TRUNCATE TABLE HF_LIST DROP STORAGE;

DROP SEQUENCE HF_SEQUENCE;

DROP SEQUENCE HF_JOB_ID_SEQ;

CREATE SEQUENCE HF_SEQUENCE START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER;

CREATE SEQUENCE HF_JOB_ID_SEQ START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER;